# Generated by Django 4.1 on 2022-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='type',
            field=models.CharField(choices=[('food', 'food'), ('drink', 'drink'), ('dinner', 'dinner')], default='food', max_length=6),
        ),
    ]
