# Generated by Django 4.1 on 2022-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type',
            field=models.CharField(choices=[('lunch', 'lunch'), ('drink', 'drink'), ('dinner', 'dinner')], default='lunch', max_length=6),
        ),
    ]
