# Generated by Django 4.1 on 2022-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_foods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
