# Generated by Django 4.1 on 2022-09-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_blog_tag_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='blog',
            field=models.ManyToManyField(blank=True, related_name='tags', to='food.blog'),
        ),
    ]
