# Generated by Django 4.1 on 2022-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
