# Generated by Django 4.1 on 2022-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_foods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type',
            field=models.CharField(choices=[('lunch', 'lunch'), ('drinks', 'drinks'), ('dinner', 'dinner')], default='lunch', max_length=6),
        ),
    ]
