# Generated by Django 4.1 on 2022-09-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_tag_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tag',
            new_name='tags',
        ),
    ]
