# Generated by Django 4.1 on 2022-09-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_contact_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show_text',
            field=models.BooleanField(default=False),
        ),
    ]
