# Generated by Django 4.1 on 2022-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
    ]
