# Generated by Django 4.1 on 2022-09-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_stuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('kinds', models.CharField(choices=[('instagram', 'instagram'), ('linkedin', 'linkedin'), ('google', 'google')], max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(blank=True, default='pic/default_food.png', null=True, upload_to='food/'),
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='social_media',
        ),
        migrations.AddField(
            model_name='stuff',
            name='social_media',
            field=models.ManyToManyField(to='food.socialmedia'),
        ),
    ]
