# Generated by Django 4.1 on 2022-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_socialmedia_alter_stuff_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(blank=True, default='pic/worker.png', null=True, upload_to='food/'),
        ),
    ]
