# Generated by Django 4.1 on 2022-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_stuff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(blank=True, default='pic/worker.jpg', null=True, upload_to='food/'),
        ),
    ]
