# Generated by Django 4.1 on 2022-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_stuff_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='social_media',
        ),
        migrations.AddField(
            model_name='stuff',
            name='phone_number',
            field=models.CharField(default='+01', max_length=30),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
