# Generated by Django 4.1 on 2022-10-12 15:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_stuff_social_media_stuff_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(default='your blog text!'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='phone_number',
            field=models.CharField(blank=True, default='+01', max_length=30, null=True),
        ),
    ]
